bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
  - gateway.yaml
  - virtual_service.yaml
namespace: development
# configMapGenerator:
#   - name: parakeetasr-shared-configmap
#     env: config/parakeetasr-shared-configmap.env