resources:
  - deployment.yaml
  - gateway.yaml
  - service.yaml
  - virtual_service.yaml
images:
  - name: parakeetasr
    newName: nexus-docker.shared.intouchcx.cloud/parakeetasr
    newTag: "{IMAGE-TAG}" #This variable will be overwritten via Jenkins for tagging the image with the proper version.